#+TITLE: Leanpub Watch Action

A GitHub Action to watch ongoing Leanpub builds.

* Inputs

- =api_key= (*required*): your Leanpub API key.
- =book_slug= (*required*): Your book slug. It's the part of the URL for your book after https://leanpub.com/. E.g. if your book is found at https://leanpub.com/your_book, then your book's slug is "your_book".

* Basic usage

You can use this in conjunction with the existing [[https://github.com/marketplace/actions/leanpub-preview-action][Leanpub Preview]] or [[https://github.com/marketplace/actions/leanpub-publish-action][Leanpub Publish]] actions, to watch over the triggered build. If there are any errors, this action will catch the backtrace generated by Leanpub and include it in the action log so you can examine it.

#+begin_src yaml
steps:
  - uses: zzamboni/leanpub-watch-action@v1
    with:
      api_key: ${{ secrets.LEANPUB_API_KEY }}
      book_slug: my_book_slug
#+end_src

* Examples

** Automatically using GitHub repo name as Leanpub book slug

If your GitHub repository name is the same as your Leanpub book slug, you can use the following step to automatically extract it into the =REPOSITORY_NAME= environment variable:

#+begin_src yaml
steps:
  - name: Get repo name to use as book slug
    run: echo BOOK_SLUG=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}') >> $GITHUB_ENV
    shell: bash
#+end_src

Afterwards, you can use it with =${{ env.BOOK_SLUG  }}=.

** Triggering and watching a book preview after every push

The simplest full workflow:

#+begin_src yaml
name: Build book preview on Leanpub
on: push

jobs:
  leanpub_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo name to use as book slug
        run: echo BOOK_SLUG=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}') >> $GITHUB_ENV
        shell: bash
      - name: Trigger Leanpub Preview
        uses: robert-matusewicz/leanpub-preview-action@v1.0
        with:
          api_key: ${{ secrets.LEANPUB_API_KEY }}
          book_slug: ${{ env.BOOK_SLUG }}
      - name: Monitor Leanpub build
        uses: zzamboni/leanpub-watch-action@v1
        with:
          api_key: ${{ secrets.LEANPUB_API_KEY }}
          book_slug: ${{ env.BOOK_SLUG }}
#+end_src
